-- set by using the USE keyword the DATABASE to codeup_test_db
USE codeup_test_db;

INSERT INTO albums (artist, name, release_date, sales, genre)
VALUES ('Michael Jackson', 'Thriller', 1982, 70, 'Pop, post-disco, funk, rock'),
       ('AC/DC', 'Back in Black', 1980, 50, 'Hard rock'),
       ('Whitney Houston', 'The Bodyguard', 1992, 45, 'R&B, soul, pop, soundtrack'),
       ('Meat Loaf', 'Bat Out of Hell', 1977, 44, 'Hard rock, glam rock, progressive rock'),
       ('Eagles', 'Their Greatest Hits (1971–1975)', 1976, 44, 'Country rock, soft rock, folk rock'),
       ('Pink Floyd', 'The Dark Side of the Moon', 1973, 44, 'Progressive rock'),
       ('Eagles', 'Hotel California', 1976, 42, 'Soft rock'),
       ('Bee Gees ', 'Saturday Night Fever', 1977, 40, 'Disco'),
       ('Fleetwood Mac', 'Rumours', 1977, 40, 'Soft rock'),
       ('Shania Twain', 'Come On Over', 1997, 40, 'Country, pop'),
       ('Various artists', 'Grease: The Original Soundtrack from the Motion Picture', 1978, 38, 'Rock and roll'),
       ('Led Zeppelin', 'Led Zeppelin IV', 1971, 37, 'Hard rock, heavy metal, folk rock'),
       ('Michael Jackson', 'Bad', 1987, 35, 'Pop, rhythm and blues, funk and rock'),
       ('Alanis Morissette', 'Jagged Little Pill', 1995, 33, 'Alternative rock'),
       ('Michael Jackson', 'Dangerous', 1991, 32, 'New jack swing, R&B and pop'),
       ('Celine Dion', 'Falling into You', 1996, 32, 'Pop, soft rock'),
       ('The Beatles', 'Sgt. Pepper''s Lonely Hearts Club Band', 1967, 32, 'Rock'),
       ('Various artists', 'Dirty Dancing', 1967, 32, 'Rock'),
       ('Adele', '21', 2011, 31, 'Pop, soul'),
       ('Celine Dion', 'Let’s Talk About Love', 1997, 31, 'Pop, soft rock'),
       ('Metallica', 'Metallica', 1991, 31, 'Heavy metal'),
       ('The Beatles', '1', 2000, 31, 'Rock'),
       ('The Beatles', 'Abbey Road', 1969, 31, 'Rock'),
       ('ABBA', 'Gold: Greatest Hits', 1992, 30, 'Pop, disco'),
       ('Bruce Springsteen', 'Born in the U.S.A.', 1984, 30, 'Heartland rock'),
       ('Madonna', 'The Immaculate Collection', 1990, 30, 'Pop, dance'),
       ('Pink Floyd', 'Pink Floyd', 1979, 30, 'Progressive rock'),
       ('James Horner', 'Titanic: Music from the Motion Picture', 1997, 30, 'Film score'),
       ('Dire Straits', 'Brothers in Arms', 1985, 30, 'Roots rock, blues rock, soft rock'),
       ('Nirvana', 'Nevermind', 1991, 30, 'Grunge, alternative rock'),
       ('Santana', 'Supernatural', 1999, 30, 'Latin rock'),
       ('Guns N'' Roses', 'Appetite for Destruction', 1987, 30, 'Hard rock'),
       ('Elton John', 'Goodbye Yellow Brick Road', 1973, 30, 'rock, pop rock, glam rock');

