/**
  # FANTASY
--
--
-- EACH LEAGUE

-- USERS CAN JOIN MULTIPLE LEAGUES
-- EACH LEAGUE IS ASSOCIATED WITH THE USERS WHO HAVE JOINED IT
*/
CREATE DATABASE IF NOT EXISTS fantasy_db;
USE fantasy_db;

CREATE TABLE IF NOT EXISTS users
(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE,
    password VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS leagues
(
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE,
    start_date DATETIME,
    end_date DATETIME,
    owner_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES users(id),
    PRIMARY KEY (id)
);

CREATE TABLE  IF NOT EXISTS league_users
(
    user_id INT UNSIGNED NOT NULL,
    league_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (league_id) REFERENCES leagues(id)
);